//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioAnalyzer.Client.AnalyzerProxyDetails {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnalyzerProxyDetails.IDetalis", CallbackContract=typeof(AudioAnalyzer.Client.AnalyzerProxyDetails.IDetalisCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDetalis {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/GetDetails")]
        void GetDetails();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/GetDetails")]
        System.Threading.Tasks.Task GetDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/Capture")]
        void Capture();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/Capture")]
        System.Threading.Tasks.Task CaptureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetalis/RequestMp3", ReplyAction="http://tempuri.org/IDetalis/RequestMp3Response")]
        void RequestMp3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetalis/RequestMp3", ReplyAction="http://tempuri.org/IDetalis/RequestMp3Response")]
        System.Threading.Tasks.Task RequestMp3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetalis/RequestPCM", ReplyAction="http://tempuri.org/IDetalis/RequestPCMResponse")]
        void RequestPCM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetalis/RequestPCM", ReplyAction="http://tempuri.org/IDetalis/RequestPCMResponse")]
        System.Threading.Tasks.Task RequestPCMAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDetalisCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/SendCatchingData")]
        void SendCatchingData(AudioAnalyzer.Common.Audio.AudioInterface.Model.Meter[] result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/SendFTTArgs")]
        void SendFTTArgs(AudioAnalyzer.Common.Audio.Helpers.FftEventArgs fttData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/SendMaxSapleCalculaterd")]
        void SendMaxSapleCalculaterd(AudioAnalyzer.Common.Audio.Helpers.MaxSampleEventArgs maxSampleData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/SendEncodedMP3")]
        void SendEncodedMP3(AudioAnalyzer.Common.Audio.Helpers.Mp3EncodedeEventArgs _mp3Data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDetalis/SendEncodedPCM")]
        void SendEncodedPCM(AudioAnalyzer.Common.Audio.Helpers.PCMBufferEventArgs _pcmData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDetalisChannel : AudioAnalyzer.Client.AnalyzerProxyDetails.IDetalis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetalisClient : System.ServiceModel.DuplexClientBase<AudioAnalyzer.Client.AnalyzerProxyDetails.IDetalis>, AudioAnalyzer.Client.AnalyzerProxyDetails.IDetalis {
        
        public DetalisClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DetalisClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DetalisClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DetalisClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DetalisClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetDetails() {
            base.Channel.GetDetails();
        }
        
        public System.Threading.Tasks.Task GetDetailsAsync() {
            return base.Channel.GetDetailsAsync();
        }
        
        public void Capture() {
            base.Channel.Capture();
        }
        
        public System.Threading.Tasks.Task CaptureAsync() {
            return base.Channel.CaptureAsync();
        }
        
        public void RequestMp3() {
            base.Channel.RequestMp3();
        }
        
        public System.Threading.Tasks.Task RequestMp3Async() {
            return base.Channel.RequestMp3Async();
        }
        
        public void RequestPCM() {
            base.Channel.RequestPCM();
        }
        
        public System.Threading.Tasks.Task RequestPCMAsync() {
            return base.Channel.RequestPCMAsync();
        }
    }
}
